"use client";

// React imports
import { useState, useEffect } from "react";

// AntD imports
import { Empty, Skeleton, Typography } from "antd";

export default function AbstractFetch(url) {
  const [data, setData] = useState(null);
  const [isLoading, setLoading] = useState(true);

  useEffect(() => {
    fetchData(url)
      .then((data) => {
        setData(data);
        setLoading(false);
        console.log("Data fetched ", data);
      })
      .catch((error) => {
        console.error(
          "This is a custom message generated by the developer. Failure to fetch data.",
          error
        );
      });
  }, [url]);

  if (isLoading) return <Skeleton active />;
  if (!data) return <Empty />;

  return data;
}
