"use client";

// React imports
import { useState, useEffect } from "react";

// Project imports
import { fetchData } from "../services/fetchData";
import { pageStyle, textStyle } from "../styles/globalStyles";
import { BuildSingleEntryURL, ABOUT_ID } from "../services/buildURL";

// AntD Imports
import { Empty, Skeleton, Typography } from "antd";
const { Title, Paragraph } = Typography;

export default function About() {
  console.log("About page rendered...");

  // For holding fetched data and loading state
  const [data, setData] = useState(null);
  const [isLoading, setLoading] = useState(true);

  useEffect(() => {
    fetchData(BuildSingleEntryURL(ABOUT_ID))
      .then((data) => {
        setData(data);
        setLoading(false);
        console.log("Data fetched ", data);
      })
      .catch((error) => {
        console.error(
          "This is a custom message generated by the developer. Failure to fetch data.",
          error
        );
      });
  }, []);

  if (isLoading) return <Skeleton active />;
  if (!data) return <Empty />;

  return (
    <div style={pageStyle}>
      <Typography>
        <Title>{data.fields.title}</Title>
        <Paragraph style={textStyle}>{data.fields.body}</Paragraph>
      </Typography>
    </div>
  );
}
