import Header from "@/app/components/header";

export const metadata = {
  title: "Sotla Lab",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
